name: Deployment Test

on:
  - push
  - workflow_dispatch

jobs:
  arc_deploy:
    name: Architect Deploy
    env:
      working_directory: ./scripts/deployment-test
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install latest version of npm
        run: npm install -g npm@latest

      - name: Deploy to Arc
        run: node ./arc.mjs
        env:
          CI: true
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}

  cf_pages_deploy:
    name: "CF Pages Deploy"
    env:
      working_directory: ./scripts/deployment-test
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install latest version of npm
        run: npm install -g npm@latest

      - name: Deploy to Cloudflare Pages
        run: node ./cf-pages.mjs
        env:
          CF_ACCOUNT_ID: ${{ secrets.TEST_CF_ACCOUNT_ID }}
          CF_GLOBAL_API_KEY: ${{ secrets.TEST_CF_GLOBAL_API_KEY }}
          CF_EMAIL: ${{ secrets.TEST_CF_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.TEST_CF_GITHUB_TOKEN }}

  cf_workers_deploy:
    name: "CF Workers Deploy"
    env:
      working_directory: ./scripts/deployment-test
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install latest version of npm
        run: npm install -g npm@latest

      - name: Deploy to Cloudflare Workers
        run: node ./cf-workers.mjs
        env:
          CF_ACCOUNT_ID: ${{ secrets.TEST_CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.TEST_CF_API_TOKEN }}

  fly_deploy:
    name: "Fly Deploy"
    env:
      working_directory: ./scripts/deployment-test
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install latest version of npm
        run: npm install -g npm@latest

      - name: Install the Fly CLI
        run: curl -L https://fly.io/install.sh | FLYCTL_INSTALL=/usr/local sh

      - name: Deploy to Fly
        run: node ./fly.mjs
        env:
          FLY_API_TOKEN: ${{ secrets.TEST_FLY_TOKEN }}

  netlify_deploy:
    name: "Netlify Deploy"
    env:
      working_directory: ./scripts/deployment-test
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install latest version of npm
        run: npm install -g npm@latest

      - name: Deploy to Netlify
        run: node ./netlify.mjs
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.TEST_NETLIFY_TOKEN }}

  vercel_deploy:
    name: "Vercel Deploy"
    env:
      working_directory: ./scripts/deployment-test
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install latest version of npm
        run: npm install -g npm@latest

      - name: Deploy to Vercel
        run: node ./vercel.mjs
        env:
          VERCEL_TOKEN: ${{ secrets.TEST_VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.TEST_VERCEL_USER_ID }}
